#### Import Packages :

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline
from pandasql import sqldf

pd.set_option('display.max_rows', 200)
print('Packages Loaded')

Packages Loaded

#### Read CSV File :

In [5]:
df_22 = pd.read_csv('2022.csv')
df_22.index.name = 'Index'
df_22.columns = df_22.columns.str.capitalize()

df_21 = pd.read_csv('2021.csv', dtype = object)
df_21.index.name = 'Index'
df_21.columns = df_22.columns.str.capitalize()

df_20 = pd.read_csv('2020.csv', dtype = object)
df_20.index.name = 'Index'
df_20.columns = df_22.columns.str.capitalize()

df_19 = pd.read_csv('2019.csv', dtype = object)
df_19.index.name = 'Index'
df_19.columns = df_22.columns.str.capitalize()

mysql = lambda q: sqldf(q, globals())

In [6]:
df_21.head()

,Incident_number,Offense_code,Offense_code_group,Offense_description,District,Reporting_area,Shooting,Occurred_on_date,Year,Month,Day_of_week,Hour,Ucr_part,Street,Lat,Long,Location
Index,,,,,,,,,,,,,,,,,
0,PLTEST005,520,NaN,BURGLARY - RESIDENTIAL,B2,289,1,2021-10-13 00:00:00,2021,10,Wednesday,0,NaN,SCHROEDER PLZ,42.33367921810846,-71.09187754618458,"(42.33367921810846, -71.09187754618458)"
1,PLTEST003,3114,NaN,INVESTIGATE PROPERTY,B2,289,0,2021-05-12 00:00:00,2021,5,Wednesday,0,NaN,SCHROEDER PLZ,42.33367921810846,-71.09187754618458,"(42.33367921810846, -71.09187754618458)"
2,PLTEST002,3114,NaN,INVESTIGATE PROPERTY,B2,289,0,2021-05-12 00:00:00,2021,5,Wednesday,0,NaN,SCHROEDER PLZ,42.33367921810846,-71.09187754618458,"(42.33367921810846, -71.09187754618458)"
3,PLTEST001,3114,NaN,INVESTIGATE PROPERTY,B2,,0,2021-03-29 00:00:00,2021,3,Monday,0,NaN,SCHROEDER PLAZA,0,0,"(0, 0)"
4,312030979,3201,NaN,PROPERTY - LOST/ MISSING,E13,465,0,2021-03-22 00:00:00,2021,3,Monday,0,NaN,BLUE HILL AVE,42.28482576580488,-71.09137368938802,"(42.28482576580488, -71.09137368938802)"

In [8]:
df_22.rename(columns = {'Offense_description':'Offense', 'Offense_code':'Code'}, inplace = True)
df_21.rename(columns = {'Offense_description':'Offense', 'Offense_code':'Code'}, inplace = True)
df_20.rename(columns = {'Offense_description':'Offense', 'Offense_code':'Code'}, inplace = True)
df_19.rename(columns = {'Offense_description':'Offense', 'Offense_code':'Code'}, inplace = True)

In [9]:
df_21.head()

,Incident_number,Code,Offense_code_group,Offense,District,Reporting_area,Shooting,Occurred_on_date,Year,Month,Day_of_week,Hour,Ucr_part,Street,Lat,Long,Location
Index,,,,,,,,,,,,,,,,,
0,PLTEST005,520,NaN,BURGLARY - RESIDENTIAL,B2,289,1,2021-10-13 00:00:00,2021,10,Wednesday,0,NaN,SCHROEDER PLZ,42.33367921810846,-71.09187754618458,"(42.33367921810846, -71.09187754618458)"
1,PLTEST003,3114,NaN,INVESTIGATE PROPERTY,B2,289,0,2021-05-12 00:00:00,2021,5,Wednesday,0,NaN,SCHROEDER PLZ,42.33367921810846,-71.09187754618458,"(42.33367921810846, -71.09187754618458)"
2,PLTEST002,3114,NaN,INVESTIGATE PROPERTY,B2,289,0,2021-05-12 00:00:00,2021,5,Wednesday,0,NaN,SCHROEDER PLZ,42.33367921810846,-71.09187754618458,"(42.33367921810846, -71.09187754618458)"
3,PLTEST001,3114,NaN,INVESTIGATE PROPERTY,B2,,0,2021-03-29 00:00:00,2021,3,Monday,0,NaN,SCHROEDER PLAZA,0,0,"(0, 0)"
4,312030979,3201,NaN,PROPERTY - LOST/ MISSING,E13,465,0,2021-03-22 00:00:00,2021,3,Monday,0,NaN,BLUE HILL AVE,42.28482576580488,-71.09137368938802,"(42.28482576580488, -71.09137368938802)"

In [10]:
df_22.head()

,Incident_number,Code,Offense_code_group,Offense,District,Reporting_area,Shooting,Occurred_on_date,Year,Month,Day_of_week,Hour,Ucr_part,Street,Lat,Long,Location
Index,,,,,,,,,,,,,,,,,
0,S87066666,3301,NaN,VERBAL DISPUTE,B2,300,0,2022-04-07 19:30:00,2022,4,Thursday,19,NaN,THORNTON PLACE,0.000000,0.000000,"(0, 0)"
1,225520077,3126,NaN,WARRANT ARREST - OUTSIDE OF BOSTON WARRANT,D14,786,0,2022-02-02 00:00:00,2022,2,Wednesday,0,NaN,WASHINGTON ST,42.343081,-71.141723,"(42.34308127134165, -71.14172267328729)"
2,222924960,3301,NaN,VERBAL DISPUTE,C11,355,0,2022-04-09 16:30:00,2022,4,Saturday,16,NaN,GIBSON ST,42.297555,-71.059709,"(42.29755532959655, -71.05970910242573)"
3,222648862,3831,NaN,M/V - LEAVING SCENE - PROPERTY DAMAGE,B2,288,0,2022-02-05 18:25:00,2022,2,Saturday,18,NaN,WASHINGTON ST,42.329748,-71.084540,"(42.329748204791635, -71.08454011649543)"
4,222201764,724,NaN,AUTO THEFT,C6,200,0,2022-01-09 00:00:00,2022,1,Sunday,0,NaN,W BROADWAY,42.341288,-71.054679,"(42.341287504390436, -71.05467932649397)"

In [11]:
df_20.head()

,Incident_number,Code,Offense_code_group,Offense,District,Reporting_area,Shooting,Occurred_on_date,Year,Month,Day_of_week,Hour,Ucr_part,Street,Lat,Long,Location
Index,,,,,,,,,,,,,,,,,
0,854652314,3115,NaN,INVESTIGATE PERSON,B2,289,0,2020-02-20 00:00:00,2020,2,Thursday,0,NaN,SCHROEDER PLZ,42.3336792181085,-71.0918775461846,"(42.3336792181085, -71.0918775461846)"
1,457856954,3115,NaN,INVESTIGATE PERSON,B2,289,0,2020-02-21 01:42:00,2020,2,Friday,1,NaN,SCHROEDER PLZ,42.3336792181085,-71.0918775461846,"(42.3336792181085, -71.0918775461846)"
2,302030654,1106,NaN,FRAUD - CREDIT CARD / ATM FRAUD,D4,167,0,2020-04-24 13:00:00,2020,4,Friday,13,NaN,MASSACHUSETTS AVE,42.3395419898301,-71.0694087696754,"(42.3395419898301, -71.0694087696754)"
3,212025777,1108,NaN,FRAUD - WELFARE,A7,28,0,2020-05-01 00:00:00,2020,5,Friday,0,NaN,TRENTON ST,42.3708180467024,-71.0392907813515,"(42.3708180467024, -71.0392907813515)"
4,212025557,2670,NaN,HARASSMENT/ CRIMINAL HARASSMENT,A1,77,0,2020-09-07 00:00:00,2020,9,Monday,0,NaN,PRINCE ST,42.3618385665647,-71.0597648909416,"(42.3618385665647, -71.0597648909416)"

In [12]:
df_19.head()

,Incident_number,Code,Offense_code_group,Offense,District,Reporting_area,Shooting,Occurred_on_date,Year,Month,Day_of_week,Hour,Ucr_part,Street,Lat,Long,Location
Index,,,,,,,,,,,,,,,,,
0,102091671,2647,NaN,THREATS TO DO BODILY HARM,B3,417,0,2019-11-12 12:00:00,2019,11,Tuesday,12,NaN,MORA ST,42.28208197671972,-71.07364874515646,"(42.28208197671972, -71.07364874515646)"
1,102095489,3115,NaN,INVESTIGATE PERSON,E18,520,0,2019-11-25 16:30:00,2019,11,Monday,16,NaN,POYDRAS ST,42.256215920402155,-71.12401947329023,"(42.256215920402155, -71.12401947329023)"
2,102096818,2905,NaN,VAL - VIOLATION OF AUTO LAW,A1,,0,2019-11-30 21:00:00,2019,11,Saturday,21,NaN,SUDBURY ST & CAMBRIDGE ST\nBOSTON MA 02108\nU...,42.360866027118476,-71.0613160019785,"(42.360866027118476, -71.0613160019785)"
3,129092894,3201,NaN,PROPERTY - LOST/ MISSING,NaN,503,0,2019-11-16 13:30:00,2019,11,Saturday,13,NaN,AMERICAN LEGION HWY,42.28446742674232,-71.11183088758158,"(42.28446742674232, -71.11183088758158)"
4,129099920,3301,NaN,VERBAL DISPUTE,B2,330,0,2019-12-12 07:50:00,2019,12,Thursday,7,NaN,COLUMBIA ROAD,0,0,"(0, 0)"

#### Clean the CSV Files :

In [22]:
query = '''
SELECT Code, Offense, Year, Month, Lat, Long
FROM df_19
WHERE Lat <> 0 AND Code NOT IN (612, 99999)
UNION ALL
SELECT Code, Offense, Year, Month, Lat, Long
FROM df_20
WHERE Lat <> 0 AND Code NOT IN (612, 99999)
UNION ALL
SELECT Code, Offense, Year, Month, Lat, Long
FROM df_21
WHERE Lat <> 0 AND Code NOT IN (612, 99999)
UNION ALL
SELECT Code, Offense, Year, Month, Lat, Long
FROM df_22
WHERE Lat <> 0 AND Code NOT IN (612, 99999)
ORDER BY Year DESC
'''
Clean_Boston_Crime_Data = mysql(query)
Clean_Boston_Crime_Data

,Code,Offense,Year,Month,Lat,Long
0,520,BURGLARY - RESIDENTIAL,2021,10,42.33367921810846,-71.09187754618458
1,3114,INVESTIGATE PROPERTY,2021,5,42.33367921810846,-71.09187754618458
2,3114,INVESTIGATE PROPERTY,2021,5,42.33367921810846,-71.09187754618458
3,3201,PROPERTY - LOST/ MISSING,2021,3,42.28482576580488,-71.09137368938802
4,3301,VERBAL DISPUTE,2021,7,42.30638322801941,-71.06021217719662
...,...,...,...,...,...,...
177619,3114,INVESTIGATE PROPERTY,2022,4,42.286882,-71.127663
177620,3831,M/V - LEAVING SCENE - PROPERTY DAMAGE,2022,4,42.274381,-71.128112
177621,3110,SERVICE TO OTHER AGENCY,2022,1,42.3296,-71.08462
177622,3125,WARRANT ARREST - BOSTON WARRANT (MUST BE SUPPL...,2022,4,42.268642,-71.095655
177623,3115,INVESTIGATE PERSON,2022,1,42.325131,-71.099408

In [23]:
Clean_Boston_Crime_Data = Clean_Boston_Crime_Data.astype({'Code':'int32', 'Offense':'category', 'Year':'int32', 'Month':'int32', 'Lat':'float64', 'Long':'float64'})
Clean_Boston_Crime_Data.Offense = Clean_Boston_Crime_Data.Offense.str.capitalize()
Clean_Boston_Crime_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177624 entries, 0 to 177623
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Code     177624 non-null  int32
 1   Offense  177624 non-null  object
 2   Year     177624 non-null  int32
 3   Month    177624 non-null  int32
 4   Lat      177624 non-null  float64
 5   Long     177624 non-null  float64
dtypes: float64(2), int32(3), object(1)
memory usage: 6.1+ MB

In [27]:
len(Clean_Boston_Crime_Data.Code.unique())

161

In [28]:
query = '''
SELECT Code, Offense FROM Clean_Boston_Crime_Data
GROUP BY Offense
ORDER BY Offense
'''
mysql(query)

     Code                                            Offense
0    2401                                             Affray
1    3122                                 Aircraft incidents
2    2613                                       Animal abuse
3    3402        Animal incidents (dog bites, lost dog, etc)
4     900                                              Arson
5     423                               Assault - aggravated
6     413                     Assault - aggravated - battery
7     801                                   Assault - simple
8     802                           Assault simple - battery
9     724                                         Auto theft
10    727                 Auto theft - leased/rented vehicle
11    706                  Auto theft - motorcycle / scooter
12   2662                          Ballistics evidence/found
13   2672                                 Biological threats
14   2648                                        Bomb threat
15    641          Breaking and entering (b&e) motor vehicle
16    531  Breaking and entering (b&e) motor vehicle (no ...
17    540                              Burglary - commerical
18    541                    Burglary - commerical - attempt
19    540                      Burglary - commerical - force
20    520                             Burglary - residential
21    520                     Burglary - residential - force
22    522                  Burglary - residential - no force
23   2608         Child requiring assistance (fomerly chins)
24   3625                   Dangerous or hazardous condition
25   3001                                Death investigation
26   2403  Disturbing the peace/ disorderly conduct/ gath...
27   1842               Drugs - poss class a - heroin, etc.
28   1841     Drugs - poss class a - intent to mfr dist disp
29   1849               Drugs - poss class b - cocaine, etc.
30   1843     Drugs - poss class b - intent to mfr dist disp
31   1844                               Drugs - poss class c
32   1848     Drugs - poss class d - intent to mfr dist disp
33   1825            Drugs - possession of drug paraphanalia
34   1810       Drugs - possession/ sale/ manufacturing/ use
35   1810                       Drugs - sale / manufacturing
36   1831               Drugs - sick assist - other narcotic
37   3305                                        Drunkenness
38   1201                                       Embezzlement
39   2632                                       Evading fare
40   2618                     Explosives - possession or use
41   3123                    Explosives - turned in or found
42   2604                             Extortion or blackmail
43   3108                                        Fire report
44   2612                          Fire report/alarm - false
45   3016         Firearm/weapon - accidental injury / death
46   3119              Firearm/weapon - found or confiscated
47   3203                              Firearm/weapon - lost
48   1001                           Forgery / counterfeiting
49   1106                    Fraud - credit card / atm fraud
50   1102                    Fraud - false pretense / scheme
51   1107                              Fraud - impersonation
52   1108                                    Fraud - welfare
53   1109                                       Fraud - wire
54   2619                              Fugitive from justice
55   1415                                           Graffiti
56   2629                                         Harassment
57   2670                    Harassment/ criminal harassment
58   3116                        Harbor incident / violation
59   3004                     Injury bicycle no m/v involved
60   3170                               Intimidating witness
61   3115                                 Investigate person
62   3114                               Investigate property
63    990                               Justifiable homicide
64   2622         Kidnapping/custodial kidnapping/ abduction
65   3112                                  Landlord - tenant
66   3112                          Landlord - tenant service
67    619                                 Larceny all others
68    611                                Larceny pick-pocket
69    613                                Larceny shoplifting
70    617                        Larceny theft from building
71    618                 Larceny theft from coin-op machine
72    614              Larceny theft from mv - non-accessory
73    616                           Larceny theft of bicycle
74    615            Larceny theft of mv parts & accessories
75   3111                          License premise violation
76   2204                               Liquor law violation
77   2646                Liquor/alcohol - drinking in public
78   3830              M/v - leaving scene - personal injury
79   3831              M/v - leaving scene - property damage
80   3810          M/v accident - involving bicycle - injury
81   3811       M/v accident - involving bicycle - no injury
82   3820       M/v accident - involving pedestrian - injury
83   3821    M/v accident - involving pedestrian - no injury
84   3801                               M/v accident - other
85   3807                  M/v accident - other city vehicle
86   3803                     M/v accident - personal injury
87   3805                      M/v accident - police vehicle
88   3802                     M/v accident - property damage
89   3205                                  M/v plates - lost
90    122                          Manslaughter - negligence
91    121                Manslaughter - vehicle - negligence
92   2400  Migrated report - affray/disturbing the peace/...
93    400  Migrated report - aggravated assault/aggravate...
94    800        Migrated report - assault/assault & battery
95   2900               Migrated report - auto law violation
96    700                       Migrated report - auto theft
97    500   Migrated report - burglary/breaking and entering
98   1000           Migrated report - counterfeiting/forgery
99    100                Migrated report - criminal homicide
100  3000              Migrated report - death investigation
101  1800  Migrated report - drugs - possession/manufactu...
102  1200                     Migrated report - embezzlement
103  1100                            Migrated report - fraud
104  3350      Migrated report - injured/medical/sick assist
105  3200               Migrated report - investigate person
106  3100             Migrated report - investigate property
107  2500                       Migrated report - kidnapping
108   650                  Migrated report - larceny from mv
109  2950              Migrated report - motor vehicle crash
110   600                    Migrated report - other larceny
111  2600                    Migrated report - other part ii
112  3300                   Migrated report - other part iii
113   300                          Migrated report - robbery
114  1300                  Migrated report - stolen property
115  1400  Migrated report - vandalism/destruction of pro...
116  1500                Migrated report - weapons violation
117  3501                                     Missing person
118  3502                           Missing person - located
119  3503            Missing person - not reported - located
120   111                 Murder, non-negligent manslaughter
121   111                Murder, non-negligient manslaughter
122  3304                        Noisy party/radio-no arrest
123  2628                                Obscene phone calls
124  2101        Operating under the influence (oui) alcohol
125  2102          Operating under the influence (oui) drugs
126  2660                                      Other offense
127  2616                    Possession of burglarious tools
128  3029               Prisoner - suicide / suicide attempt
129  3106                       Property - accidental damage
130  3207                                   Property - found
131  3201                                    Property - lost
132  3202                       Property - lost then located
133  3201                           Property - lost/ missing
134  1304                   Property - stolen then recovered
135  1601                                       Prostitution
136  1603              Prostitution - assisting or promoting
137  1602                          Prostitution - soliciting
138  3403                   Protective custody / safekeeping
139   736  Recovered - mv recovered in boston (stolen in ...
140   735  Recovered - mv recovered in boston (stolen out...
141   301                                            Robbery
142   301                                   Robbery - street
143  3130                                     Search warrant
144  3110                            Service to other agency
145  3005                                        Sick assist
146  1832                 Sick assist - drug related illness
147  3006                      Sick/injured/medical - person
148  3018                      Sick/injured/medical - police
149  1300  Stolen property - buying / receiving / possessing
150  3007                                       Sudden death
151  3008                          Suicide / suicide attempt
152  2647                          Threats to do bodily harm
153  3410                                Towed motor vehicle
154  2610                                        Trespassing
155  2642                                  Truancy / runaway
156  2907                    Val - operating after rev/susp.
157  2914           Val - operating w/o authorization lawful
158  2905                        Val - violation of auto law
159  2900                Val - violation of auto law - other
160  1402                                          Vandalism
161  3301                                     Verbal dispute
162  2006                Viol. of restraining order w arrest
163  2657                         Violation - city ordinance
164  2671            Violation - harassment prevention order
165  2007          Violation - restraining order (no arrest)
166  3125                                     Warrant arrest
167  3125  Warrant arrest - boston warrant (must be suppl...
168  3126         Warrant arrest - outside of boston warrant
169  1501      Weapon - firearm - carrying / possessing, etc
170  1501  Weapon violation - carry/ possessing/ sale/ tr...

#### Separate into Crimes in each year :

In [16]:
query = '''
SELECT *
FROM Clean_Boston_Crime_Data
WHERE Year = 2019
ORDER BY Month, Offense
'''
Crime_19 = mysql(query)
Crime_19

,Code,Offense,Year,Month,Lat,Long
0,423,Assault - aggravated,2019,1,42.351706,-71.119900
1,801,Assault - simple,2019,1,42.349056,-71.150498
2,1106,Fraud - credit card / atm fraud,2019,1,42.339542,-71.069409
3,1106,Fraud - credit card / atm fraud,2019,1,42.351935,-71.060486
4,1102,Fraud - false pretense / scheme,2019,1,42.341288,-71.054679
...,...,...,...,...,...,...
20959,1501,Weapon violation - carry/ possessing/ sale/ tr...,2019,12,42.322384,-71.080454
20960,1501,Weapon violation - carry/ possessing/ sale/ tr...,2019,12,42.278963,-71.099285
20961,1501,Weapon violation - carry/ possessing/ sale/ tr...,2019,12,42.312387,-71.070862
20962,1501,Weapon violation - carry/ possessing/ sale/ tr...,2019,12,42.322216,-71.082067
20963,1501,Weapon violation - carry/ possessing/ sale/ tr...,2019,12,42.346188,-71.148879

In [17]:
query = '''
SELECT *
FROM Clean_Boston_Crime_Data
WHERE Year = 2020
ORDER BY Month, Offense
'''
Crime_20 = mysql(query)
Crime_20

,Code,Offense,Year,Month,Lat,Long
0,2401,Affray,2020,1,42.352023,-71.064634
1,2401,Affray,2020,1,42.316966,-71.082541
2,3122,Aircraft incidents,2020,1,42.375258,-71.024663
3,3122,Aircraft incidents,2020,1,42.375258,-71.024663
4,3122,Aircraft incidents,2020,1,42.375258,-71.024663
...,...,...,...,...,...,...
69121,1501,Weapon violation - carry/ possessing/ sale/ tr...,2020,12,42.338917,-71.081149
69122,1501,Weapon violation - carry/ possessing/ sale/ tr...,2020,12,42.359884,-71.060162
69123,1501,Weapon violation - carry/ possessing/ sale/ tr...,2020,12,42.312596,-71.092876
69124,1501,Weapon violation - carry/ possessing/ sale/ tr...,2020,12,42.279138,-71.087971
69125,1501,Weapon violation - carry/ possessing/ sale/ tr...,2020,12,42.334738,-71.091971

In [18]:
query = '''
SELECT *
FROM Clean_Boston_Crime_Data
WHERE Year = 2021
ORDER BY Month, Offense
'''
Crime_21 = mysql(query)
Crime_21

,Code,Offense,Year,Month,Lat,Long
0,3402,"Animal incidents (dog bites, lost dog, etc)",2021,1,42.345567,-71.071479
1,3402,"Animal incidents (dog bites, lost dog, etc)",2021,1,42.347991,-71.062573
2,3402,"Animal incidents (dog bites, lost dog, etc)",2021,1,42.292861,-71.054229
3,3402,"Animal incidents (dog bites, lost dog, etc)",2021,1,42.297034,-71.068607
4,3402,"Animal incidents (dog bites, lost dog, etc)",2021,1,42.297555,-71.059709
...,...,...,...,...,...,...
68810,1501,Weapon violation - carry/ possessing/ sale/ tr...,2021,12,42.348776,-71.096068
68811,1501,Weapon violation - carry/ possessing/ sale/ tr...,2021,12,42.282540,-71.071360
68812,1501,Weapon violation - carry/ possessing/ sale/ tr...,2021,12,42.368902,-71.039810
68813,1501,Weapon violation - carry/ possessing/ sale/ tr...,2021,12,42.359260,-71.059400
68814,1501,Weapon violation - carry/ possessing/ sale/ tr...,2021,12,42.341995,-71.068115

In [19]:
query = '''
SELECT *
FROM Clean_Boston_Crime_Data
WHERE Year = 2022
ORDER BY Month, Offense
'''
Crime_22 = mysql(query)
Crime_22

,Code,Offense,Year,Month,Lat,Long
0,2401,Affray,2022,1,42.276860,-71.137576
1,3122,Aircraft incidents,2022,1,42.375258,-71.024663
2,2613,Animal abuse,2022,1,42.301263,-71.062210
3,3402,"Animal incidents (dog bites, lost dog, etc)",2022,1,42.256216,-71.124019
4,3402,"Animal incidents (dog bites, lost dog, etc)",2022,1,42.280209,-71.176805
...,...,...,...,...,...,...
18715,1501,Weapon violation - carry/ possessing/ sale/ tr...,2022,4,42.257191,-71.120018
18716,1501,Weapon violation - carry/ possessing/ sale/ tr...,2022,4,42.333500,-71.073510
18717,1501,Weapon violation - carry/ possessing/ sale/ tr...,2022,4,42.318553,-71.063433
18718,1501,Weapon violation - carry/ possessing/ sale/ tr...,2022,4,42.355214,-71.062064
18719,1501,Weapon violation - carry/ possessing/ sale/ tr...,2022,4,42.355123,-71.060880

#### Finding Crimes to be plotted :

In [20]:
query = '''
SELECT Code, Offense, COUNT(Code) FROM Clean_Boston_Crime_Data
GROUP BY Code
ORDER BY COUNT(Code) DESC
''' 
mysql(query).head(40)

    Code                                       Offense  COUNT(Code)
0   3115                            Investigate person        14963
1   3831         M/v - leaving scene - property damage        10441
2   3005                                   Sick assist        10048
3   3114                          Investigate property         8380
4   1402                                     Vandalism         8032
5   3410                           Towed motor vehicle         7291
6    801                              Assault - simple         6905
7    614         Larceny theft from mv - non-accessory         5625
8   3006                 Sick/injured/medical - person         5602
9    613                           Larceny shoplifting         5592
10  3201                      Property - lost/ missing         4899
11  3802                M/v accident - property damage         4788
12   617                   Larceny theft from building         4213
13  2647                     Threats to do bodily harm         4202
14   423                          Assault - aggravated         4019
15  3301                                Verbal dispute         3907
16  1810  Drugs - possession/ sale/ manufacturing/ use         3751
17   619                            Larceny all others         3593
18  1102               Fraud - false pretense / scheme         3159
19  3801                          M/v accident - other         2944
20  2670               Harassment/ criminal harassment         2770
21  2905                   Val - violation of auto law         2658
22   724                                    Auto theft         2403
23  3502                      Missing person - located         2338
24  3803                M/v accident - personal injury         2315
25   520                        Burglary - residential         2130
26  3207                              Property - found         2080
27   301                                       Robbery         1864
28  1832            Sick assist - drug related illness         1832
29   616                      Larceny theft of bicycle         1821
30  1107                         Fraud - impersonation         1575
31  1831          Drugs - sick assist - other narcotic         1502
32  3018                 Sick/injured/medical - police         1344
33  3007                                  Sudden death         1293
34  1106               Fraud - credit card / atm fraud         1206
35   615       Larceny theft of mv parts & accessories         1201
36  3108                                   Fire report         1091
37  1108                               Fraud - welfare         1085
38  3820  M/v accident - involving pedestrian - injury         1055
39  2907               Val - operating after rev/susp.         1040

##### Here, we choose the following 4 crimes :
##### 1. Larceny
##### 2. Assault
##### 3. Fraud
##### 4. Vandalism